openapi: 3.0.0
info:
  title: Recetas API
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Obtener todos los usuarios
      tags:
        - Users
      responses:
        '200':
          description: Usuarios obtenidos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error interno del servidor
  /api/users/{userId}:
    get:
      summary: Obtener un usuario específico
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Usuario obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar un usuario específico
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '204':
          description: Usuario actualizado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un usuario específico
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '204':
          description: Usuario eliminado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        profile:
          $ref: '#/components/schemas/Profile'
        recetas:
          type: array
          items:
            $ref: '#/components/schemas/Receta'
      example:
        id: 1
        email: jorge@gmail.com
        password: "hashed_password"
        active: true
        createdAt: '2023-02-02T00:00:00Z'
        updatedAt: '2023-02-02T00:00:00Z'
        profile:
          firstName: Jorge
          lastName: Lopez
          dni: "50123456"
          gender: Masculino
          address: Salta 900
          city: Salta
          country: Argentina
          cellPhone: "3884123456"
          photo: jl.jpg
        recetas: []
    UserUpdate:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: jorge@gmail.com
        password: "new_password"
    Profile:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dni:
          type: string
        gender:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        cellPhone:
          type: string
        photo:
          type: string
      example:
        firstName: Jorge
        lastName: Lopez
        dni: "50123456"
        gender: Masculino
        address: Salta 900
        city: Salta
        country: Argentina
        cellPhone: "3884123456"
        photo: jl.jpg
    Receta:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        image:
          type: string
        ingredients:
          type: string
        preparation:
          type: string
        estimatedPreparationTime:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      example:
        id: 1
        name: Pastel de Chocolate
        description: Delicioso pastel de chocolate
        image: "/path/to/image.jpg"
        ingredients: "Harina, chocolate, azúcar"
        preparation: "Mezclar ingredientes, hornear a 180°C"
        estimatedPreparationTime: 60
        createdAt: '2023-02-02T00:00:00Z'
        updatedAt: '2023-02-02T00:00:00Z'
